"""
reporting.py — Markdown Report Generator
==========================================

Converts Analyzer results into readable .md documentation.
Separates signal from suggestion throughout.
Matches the educational style of our House Prices docs.

Usage:
    from kaggle_mentor import Analyzer, Reporter

    a = Analyzer(df, target="SalePrice").run()
    r = Reporter(a.results, target="SalePrice")
    r.save("EDA_REPORT.md")
    print(r.render())
"""

from datetime import datetime
from typing import Optional


CONFIDENCE_EMOJI = {
    "high":   "🟢",
    "medium": "🟡",
    "low":    "🔴",
}


class Reporter:
    """
    Generates a structured markdown report from Analyzer results.

    Parameters
    ----------
    results : dict
        Output from Analyzer.results
    target : str
        Target column name (for display)
    competition : str, optional
        Competition name for report header
    """

    def __init__(self, results: dict, target: str,
                 competition: str = "Kaggle Competition"):
        self.results = results
        self.target = target
        self.competition = competition

    def render(self) -> str:
        """Render the full markdown report as a string."""
        sections = [
            self._header(),
            self._meta_section(),
            self._target_section(),
            self._missing_section(),
            self._correlation_section(),
            self._multicollinearity_section(),
            self._skewness_section(),
            self._encoding_section(),
            self._outlier_section(),
            self._action_plan(),
            self._footer(),
        ]
        return "\n\n".join(sections)

    def save(self, path: str = "EDA_REPORT.md"):
        """Save the report to a markdown file."""
        content = self.render()
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✅ Report saved: {path}")
        return path

    # -----------------------------------------------------------------------
    # Sections
    # -----------------------------------------------------------------------

    def _header(self) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M")
        return f"""# EDA Report — {self.competition}

*Generated by kaggle_mentor on {ts}*

> **Signal** = objective observation from data  
> **Suggestion** = heuristic recommendation (includes confidence + reasoning)  
> Confidence: 🟢 High | 🟡 Medium | 🔴 Low"""

    def _meta_section(self) -> str:
        m = self.results.get("meta", {})
        return f"""## 📊 Dataset Overview

| Metric | Value |
|--------|-------|
| Samples | {m.get('n_samples', '?'):,} |
| Features | {m.get('n_features', '?')} |
| Numeric | {m.get('n_numeric', '?')} |
| Categorical | {m.get('n_categorical', '?')} |
| Problem Type | {m.get('problem_type', '?')} |
| Target | `{m.get('target', '?')}` |"""

    def _target_section(self) -> str:
        t = self.results.get("target", {})
        sig = t.get("signal", {})
        emoji = CONFIDENCE_EMOJI.get(t.get("confidence", "low"), "🔴")

        return f"""## 🎯 Target Variable: `{self.target}`

### Signal (Objective)

| Metric | Value |
|--------|-------|
| Min | {sig.get('min', '?'):,.0f} |
| Max | {sig.get('max', '?'):,.0f} |
| Mean | {sig.get('mean', '?'):,.0f} |
| Median | {sig.get('median', '?'):,.0f} |
| Std Dev | {sig.get('std', '?'):,.0f} |
| Skewness | {sig.get('skewness', '?')} |
| Kurtosis | {sig.get('kurtosis', '?')} |

### Suggestion

{emoji} **Confidence: {t.get('confidence', '?').upper()}**

**Recommendation:** {t.get('suggestion', '?')}

**Reasoning:** {t.get('reasoning', '?')}"""

    def _missing_section(self) -> str:
        missing = self.results.get("missing", [])
        if not missing:
            return "## 🔍 Missing Values\n\n✅ No missing values detected."

        lines = ["## 🔍 Missing Values\n"]
        lines.append(f"**{len(missing)} missing value group(s) detected.**\n")
        lines.append("| Columns | Missing % | Pattern | Confidence | Suggestion |")
        lines.append("|---------|-----------|---------|------------|------------|")

        for item in missing:
            cols = ", ".join(f"`{c}`" for c in item["columns"][:3])
            if len(item["columns"]) > 3:
                cols += f" +{len(item['columns'])-3} more"
            emoji = CONFIDENCE_EMOJI.get(item["confidence"], "🔴")
            lines.append(
                f"| {cols} | {item['pct']}% | {item['pattern']} "
                f"| {emoji} {item['confidence']} | {item['suggestion'][:60]}... |"
            )

        lines.append("\n### Details\n")
        for item in missing:
            cols_str = ", ".join(f"`{c}`" for c in item["columns"])
            emoji = CONFIDENCE_EMOJI.get(item["confidence"], "🔴")
            lines.append(f"**{cols_str}**")
            lines.append(f"- Signal: {item['signal']}")
            lines.append(f"- Suggestion: {item['suggestion']}")
            lines.append(f"- {emoji} Reasoning: *{item['reasoning']}*\n")

        return "\n".join(lines)

    def _correlation_section(self) -> str:
        corrs = self.results.get("correlations", [])
        if not corrs:
            return "## 📈 Correlations\n\n*Not applicable for this problem type.*"

        lines = [f"## 📈 Top Correlations with `{self.target}`\n"]
        lines.append("> Note: Pearson measures **linear** correlation only. "
                     "Tree models may find additional non-linear signal.\n")
        lines.append("| Rank | Feature | Correlation | Strength |")
        lines.append("|------|---------|-------------|----------|")

        for i, item in enumerate(corrs[:15], 1):
            bar = "█" * int(abs(item["correlation"]) * 10)
            lines.append(
                f"| {i} | `{item['feature']}` | "
                f"{item['correlation']:>6.3f} {bar} | {item['strength']} |"
            )

        return "\n".join(lines)

    def _multicollinearity_section(self) -> str:
        multi = self.results.get("multicollinearity", [])
        lines = ["## ⚠️ Multicollinearity\n"]

        if not multi:
            lines.append("✅ No high multicollinearity detected (threshold: r > 0.8)")
            return "\n".join(lines)

        lines.append(f"**{len(multi)} high-correlation pair(s) detected.**\n")
        lines.append("| Feature 1 | Feature 2 | r | Confidence |")
        lines.append("|-----------|-----------|---|------------|")

        for item in multi:
            emoji = CONFIDENCE_EMOJI.get(item["confidence"], "🔴")
            lines.append(
                f"| `{item['feature_1']}` | `{item['feature_2']}` "
                f"| {item['correlation']} | {emoji} {item['confidence']} |"
            )

        lines.append("\n### Options (not directives)\n")
        for item in multi:
            lines.append(f"**`{item['feature_1']}` ↔ `{item['feature_2']}`** (r={item['correlation']})")
            lines.append(f"- {item['suggestion']}")
            lines.append(f"- *{item['reasoning']}*\n")

        return "\n".join(lines)

    def _skewness_section(self) -> str:
        skewed = self.results.get("skewed_features", [])
        lines = ["## 📐 Skewed Features\n"]

        if not skewed:
            lines.append("✅ No highly skewed features detected (threshold: |skewness| > 0.75)")
            return "\n".join(lines)

        lines.append(f"**{len(skewed)} feature(s) with |skewness| > 0.75 — recommend `log1p` transform.**\n")
        lines.append("> Primarily benefits linear models. Tree models are less sensitive.\n")
        lines.append("| Feature | Skewness | Confidence |")
        lines.append("|---------|----------|------------|")

        for item in skewed[:20]:
            emoji = CONFIDENCE_EMOJI.get(item["confidence"], "🔴")
            lines.append(
                f"| `{item['feature']}` | {item['skewness']:>8.3f} "
                f"| {emoji} {item['confidence']} |"
            )

        if len(skewed) > 20:
            lines.append(f"\n*...and {len(skewed)-20} more features*")

        return "\n".join(lines)

    def _encoding_section(self) -> str:
        encoding = self.results.get("encoding", [])
        if not encoding:
            return "## 🔤 Encoding\n\n*No categorical features detected.*"

        lines = ["## 🔤 Encoding Recommendations\n"]

        # Group by strategy
        by_strategy = {}
        for item in encoding:
            by_strategy.setdefault(item["strategy"], []).append(item)

        strategy_order = ["ordinal", "binary", "one_hot", "target"]
        strategy_labels = {
            "ordinal":  "Ordinal Encoding (natural order detected)",
            "binary":   "Binary Encoding (2 categories)",
            "one_hot":  "One-Hot Encoding (low cardinality)",
            "target":   "Target Encoding (high cardinality)",
        }

        for strategy in strategy_order:
            items = by_strategy.get(strategy, [])
            if not items:
                continue
            lines.append(f"### {strategy_labels.get(strategy, strategy)}\n")
            lines.append("| Feature | Categories | Confidence |")
            lines.append("|---------|------------|------------|")
            for item in items:
                emoji = CONFIDENCE_EMOJI.get(item["confidence"], "🔴")
                lines.append(
                    f"| `{item['feature']}` | {item['n_categories']} "
                    f"| {emoji} {item['confidence']} |"
                )
            lines.append("")

        return "\n".join(lines)

    def _outlier_section(self) -> str:
        outliers = self.results.get("outliers", [])
        lines = ["## 🔎 Outliers\n"]

        if not outliers:
            lines.append("✅ No outliers detected (3×IQR threshold)")
            return "\n".join(lines)

        lines.append(f"**{len(outliers)} feature(s) with outliers detected (3×IQR method).**\n")
        lines.append("> Outliers may be legitimate data points. "
                     "Investigate before removing.\n")
        lines.append("| Feature | Count | % of Data |")
        lines.append("|---------|-------|-----------|")

        for item in outliers[:10]:
            lines.append(
                f"| `{item['feature']}` | {item['n_outliers']} | {item['pct']}% |"
            )

        lines.append(
            "\n**Handling options:**\n"
            "- Linear models: consider removing or capping (sensitive to outliers)\n"
            "- Tree models: usually safe to keep (robust to outliers)\n"
            "- Always investigate: outliers may reveal data quality issues"
        )

        return "\n".join(lines)

    def _action_plan(self) -> str:
        """Generate a prioritized action plan from all findings."""
        lines = ["## 🚀 Recommended Action Plan\n"]
        lines.append("*Priority order based on expected impact:*\n")

        priority = 1

        # Target transform
        t = self.results.get("target", {})
        if "log" in t.get("suggestion", ""):
            lines.append(f"{priority}. **Log transform target** — `y = np.log1p(df['{self.target}'])`")
            lines.append(f"   {CONFIDENCE_EMOJI['high']} High confidence | Expected impact: 20-30% RMSE improvement\n")
            priority += 1

        # Missing values
        missing = self.results.get("missing", [])
        if missing:
            lines.append(f"{priority}. **Handle missing values** ({len(missing)} groups)")
            for item in missing[:3]:
                cols = ", ".join(f"`{c}`" for c in item["columns"][:2])
                lines.append(f"   - {cols}: {item['suggestion'][:70]}")
            lines.append("")
            priority += 1

        # Skewed features
        skewed = self.results.get("skewed_features", [])
        if skewed:
            lines.append(f"{priority}. **Log1p transform {len(skewed)} skewed features**")
            lines.append(f"   `for col in skewed_cols: df[col] = np.log1p(df[col])`\n")
            priority += 1

        # Multicollinearity
        multi = self.results.get("multicollinearity", [])
        if multi:
            lines.append(f"{priority}. **Address multicollinearity** ({len(multi)} pairs)")
            for item in multi[:2]:
                lines.append(
                    f"   - `{item['feature_1']}` ↔ `{item['feature_2']}` "
                    f"(r={item['correlation']}): {item['suggestion'][:60]}..."
                )
            lines.append("")
            priority += 1

        # Encoding
        encoding = self.results.get("encoding", [])
        target_enc = [e for e in encoding if e["strategy"] == "target"]
        ordinal_enc = [e for e in encoding if e["strategy"] == "ordinal"]
        if ordinal_enc:
            lines.append(f"{priority}. **Ordinal encode** {len(ordinal_enc)} quality features\n")
            priority += 1
        if target_enc:
            lines.append(
                f"{priority}. **Target encode** {len(target_enc)} high-cardinality features: "
                + ", ".join(f"`{e['feature']}`" for e in target_enc[:3]) + "\n"
            )
            priority += 1

        return "\n".join(lines)

    def _footer(self) -> str:
        return (
            "---\n"
            "*Generated by [kaggle_mentor](https://github.com/your-repo/kaggle_mentor)*  \n"
            "*Signal = objective | Suggestion = heuristic | Always validate with your domain knowledge*"
        )
